#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Phoneword.Resource", IsApplication=true)]

namespace Phoneword
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int Icon = 2130771968;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F02000C
			public const int button1 = 2130837516;
			
			// aapt resource value: 0x7F020000
			public const int C1 = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int C2 = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int C3 = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int CalculateButton = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int Coef1 = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int Coef2 = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int Coef3 = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int CoefficientA = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int CoefficientB = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int DyhotomyResult = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int Epsilon = 2130837514;
			
			// aapt resource value: 0x7F02000D
			public const int item1 = 2130837517;
			
			// aapt resource value: 0x7F02000B
			public const int IterationsNumber = 2130837515;
			
			// aapt resource value: 0x7F02000E
			public const int linearLayout1 = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int textView1 = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int textView2 = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int textView3 = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int textView4 = 2130837522;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
